import initScrollSuave from './modules/scroll-suave.js';
import menufixo from './modules/menu-fixado.js';
import initAnimeScroll from './modules/scroll-animacao.js';
import projetosanimacaoButton from './modules/animacao-projetos.js';
import certificateanimacaoButton from './modules/animacao-certificados.js';
import habilidadesanimacaoButton from './modules/animacao-habilidades.js';
import animacaoMenuScroll from './modules/scroll-menu-scroll.js';
import maquinaEscrever from './modules/maquina-escrever.js';
import habilidades from './modules/habilidades.js';
import formulario from './modules/formulario.js';
import initMenuMobile from './modules/menu-mobile.js';
import vanillaTilt from './modules/efeito-imagem.js';
import sonsBotoes from './modules/sons-botoes.js';

initScrollSuave();
menufixo();
initAnimeScroll();
projetosanimacaoButton();
certificateanimacaoButton();
habilidadesanimacaoButton();
animacaoMenuScroll();
maquinaEscrever();
habilidades();
formulario();
initMenuMobile();
vanillaTilt();
sonsBotoes();
